# Generated by Django 4.2.2 on 2023-06-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년'), ('5', '5학년')], default='1', max_length=20)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
