# Generated by Django 4.2.2 on 2023-06-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('male', '남'), ('female', '여')], default='', max_length=20),
        ),
    ]
