# Generated by Django 4.2.2 on 2023-07-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.JSONField(default=dict),
        ),
    ]
