# Generated by Django 4.2.2 on 2023-07-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_student_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('limit', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('permit_subject', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
