# Generated by Django 4.2.2 on 2023-07-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_course_permit_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년'), ('5', '5학년')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
